---
- name: Deploy application
  hosts: app
  gather_facts: no

  tasks:
    - name: Install git
      become: true
      apt:
        state: present
        name: git>=1.7.1

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
    - name: reload puma
      become: true
      systemd:
        name: puma
        state: restarted
